[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*" # see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
[[redirects]]
  from = "/api/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true