[[redirects]]
  from = "/api/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true
  headers = { Authorization = "e0b4651c4b5048b9be7029a55f2a3270" }

[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*"